---
name: "release"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - run: go install go.k6.io/xk6/cmd/xk6@latest
      - run: xk6 build --with github.com/grafana/xk6-client-prometheus-remote@latest
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - run: chmod +x k6
      - run: mv k6 k6_${{ env.TAG }}_linux_amd64
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'k6*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
