---
name: "release"

on:
  release:
    types:
      - published

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.7'
      - run: go install go.k6.io/xk6/cmd/xk6@latest
      - run: xk6 build --with github.com/grafana/xk6-client-prometheus-remote@latest
      - run: chmod +x k6
      - run: cp k6 k6_${{ github.event.release.tag_name }}_linux_amd64
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: 'k6*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:buildx"
        uses: docker/setup-buildx-action@v1
      - name: "Build:login"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build:dockerimage"
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: Dockerfile
          tags: ghcr.io/grafana/xk6-client-prometheus-remote:latest,ghcr.io/grafana/xk6-client-prometheus-remote:${{ github.event.release.tag_name }}
